name: ant_nup_tracker
description: Citizen science tool for recording ant nuptial flights.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.1
  http: ^0.13.3
  built_value: ^8.0.6
  intl: ^0.17.0
  latlong2: ^0.8.0
  recase: ^4.0.0
  image_picker: ^0.8.2
  tuple: ^2.0.0
#  flutter_map: ^0.13.1
  url_launcher: ^6.0.9
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.0+2
  location: ^4.3.0
  path: ^1.8.0
  mime: ^1.0.0
  lints: ^1.0.1
  flutter_lints: ^1.0.4
  cached_network_image: ^3.1.0
  scrollable_positioned_list: ^0.2.3
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^4.2.1
  sqflite: ^2.0.0+4
  flutter_image_compress: ^1.1.0
  timezone: ^0.8.0
  lat_lng_to_timezone: ^0.2.0
  path_provider: ^2.0.8
  permission_handler: ^9.2.0
  flutter_oss_licenses: ^2.0.0+1
  gallery_saver: ^2.3.2
  google_fonts: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^4.1.1
  build_runner: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

#   To add assets to your application, add an assets section, like this:
  assets:
     - assets/cartoon_ant/
     - assets/ant_circles/
     - assets/proprietary/openweather/
     - fonts/Dosis/OFL.txt
     - fonts/Open_Sans/LICENSE.txt
#     - images/a_dot_burr.jpeg
#     - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis/static/Dosis-Regular.ttf
        - asset: fonts/Dosis/static/Dosis-ExtraLight.ttf
          weight: 200
        - asset: fonts/Dosis/static/Dosis-Light.ttf
          weight: 300
        - asset: fonts/Dosis/static/Dosis-Medium.ttf
          weight: 500
        - asset: fonts/Dosis/static/Dosis-SemiBold.ttf
          weight: 600
        - asset: fonts/Dosis/static/Dosis-Bold.ttf
          weight: 700
        - asset: fonts/Dosis/static/Dosis-ExtraBold.ttf
          weight: 800
    - family: Open_Sans
      fonts:
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Regular.ttf
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Open_Sans/static/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: false
#  class_name: AppLocalizations
#  main_locale: en
